### ISSUE TITLE
A member who's membership is expiring receives automated renewal emails

### ISSUE THREAD

**Issue by antulik** [rubyaustralia/ruby_au#44]

**Comment by antulik** [comment]
@radar we haven't spoke about it, but that's an interesting point. Does membership expire or is indefinite?

**Comment by quintrino** [comment]
My understanding was that it expires just before each rails camp so we always have Quorum for A/S GMs.

**Comment by antulik** [comment]
@quintrino this is about normal ruby au members, not committee members

**Comment by quintrino** [comment]
I know, that was my understanding of how we always achieved quorum. Otherwise, if we have 2000 active Ruby AU members and need at least 20% percent attending at a meeting (both of those numbers chosen at random, I'm not sure what the actual numbers are) we'd never be able to hold a binding AGM.

**Comment by radar** [comment]
I've been meaning to comment on this for a while. Sorry for the delay.

I would like to point out a couple of sections of the Constitution.

Let's start with Section 9.1:

> Memberships of the Association are granted automatically to attendees at events conducted by the Association such as “the Rails Camp” or other such events as they are held from time to time.

Sections 16 and 17:

> **Section 16**
> 1. The membership of a person ceases on resignation, expulsion or death.
> 2. If a person ceases to be a member of the Association, the Secretary must, as soon as practicable, enter the date the person ceased to be a member in the register of members.

> **Section 17**
> 1. A member may resign by notice in writing given to the Association.
> 2. A member is taken to have resigned if the Secretary has made a written request to the member to confirm that they wish to remain a member and a response is not received within the timeframe nominated by the Secretary in the request.

These sections cover membership for Ruby AU for non-committee members. I included Section 9.1 as it's important to note that _anyone_ attending Ruby AU events is automatically a member. They do not have to be on the membership register already to be eligible to vote. Simply by attending they are eligible. I think because of this section we should do our best to add attendees of RailsCamps to the membership register, but that it should be an opt-in thing.

Going by Section 16.1 I would say that is an indicator that membership does not automatically expire; rather it is an opt-out type of thing. Section 17 outlines how someone can resign.

---

Regarding quorum, Section 36.2 says:

> The quorum for a general meeting is the presence of nine members entitled to vote.

Nine members, not necessarily of the committee, have to be present. We do not have to have 20% of the membership base in attendance. General Meetings being either the Annual General Meeting or Special General Meeting, which happen at every RailsCamps, with AGM/SGM alternating every camp. Judging by [this forum thread](https://forum.ruby.org.au/t/ruby-australia-sgm-7th-may-2017/229) the last RailsCamp was an SGM, so the next one will have an AGM.

I should also point out at this stage that Section 34 covers how people who cannot be physically present at the meetings are still entitled to vote via proxy. This is very helpful for instance for fathers who need to look after their daughters during their wife's exam time, when that exam time coincides with RailsCamps ;)

Anyway, that's all I can find in the Constitution regarding membership expirations and quorum requirements. I hope that helps you out.

**Comment by quintrino** [comment]
Ah, that clarifies all of my questions.

**Comment by antulik** [comment]
Thanks @radar. This ticket is no longer relevant then.
