### ISSUE TITLE
Admin can import event attendees csv

### ISSUE THREAD

**Issue by antulik** [rubyaustralia/ruby_au#56]
@tcn33 could you please provide a sample csv file

**Comment by tcn33** [comment]
[Archive.zip](https://github.com/rubyaustralia/ruby_au/files/1248451/Archive.zip)

Here's a sample from RailsCamps 21 and 22. (Zipped as Github doesn't allow CSV)

A couple of things to note here:
- Fields in ti.to are heavily user configurable. Out of the box you can expect the first 28 fields to be the same (though whether or not they are populated is up to the event organiser) and everything else should be custom (e.g t-shirt sizes) and therefore safely disregarded.
- You'll want to use Ticket First Name and Ticket Last Name (fifth and sixth fields) rather than Order First Name and Order Last Name. The first two are the actual attendee, the others are who paid for the ticket.

One other thing is that this should be considered a stopgap - manually exporting and importing CSV data is not a permanent solution. ti.to provides [webhooks](https://ti.to/docs/webhook) which _would_ be an ideal solution, if not for the fact that they'd have to be manually configured for each individual event - easy to mess up and even easier to forget. 

The best solution is probably the ti.to [API](http://teamtito.github.io/tito-api-docs/), which is a work in progress but seems to be fairly feature complete.

**Comment by antulik** [comment]
is ruby conf au also using ti.to?

**Comment by tcn33** [comment]
Yes. If necessary I can get you a sample export from a past conf.

On Thu, Aug 24, 2017 at 20:28, Anton Katunin <notifications@github.com> wrote:
is ruby conf au also using ti.to?

**Comment by antulik** [comment]
please send if it's different to the archive above. I see your point about automating the whole process and kinda agree. Will look into the webhooks first. Otherwise csv import is not as bad considering we only have to do 3 imports per year.

**Comment by pat** [comment]
This is now covered (at least at a basic level) by #102 (granted, @antulik had already done the hard work in an outdated PR #58, I just didn't notice it until now).

Agreed that working with Tito's API would be ideal (and Meetup's, Slack's, Discourse's), so we can auto-invite members from wherever they're interacting. I'm keen to help make that happen but almost certainly won't be until after the upcoming AGM.
